title: Connect the dots in a GitHub repository
tagline: Learn how to navigate through a repository's history and context.
description: This course will teach you skills for finding relevant conversations, commits, and projects in a repository.
template:
  name: connect-the-dots-in-a-github-repository
  repo: connect-the-dots-in-a-github-repository-template
before:
  - type: createIssue
    title: Welcome
    body: 00_welcome-issue.md
  - type: createIssue
    title: Welcome to this repository
    body: 00_existing-welcome.md
  - type: createPullRequest
    title: Create documentation structure
    body: 00_create-documentation-structure.md
    head: create-documentation-structure
  - type: mergeBranch
    head: create-documentation-structure
  - type: deleteBranch
    branch: create-documentation-structure
  - type: createPullRequest
    title: Add new pages
    body: 00_add-new-pages.md
    head: add-new-pages
  - type: mergeBranch
    head: add-new-pages
  - type: deleteBranch
    branch: add-new-pages
  - type: createPullRequest
    title: Add navigation
    body: 00_add-navigation.md
    head: add-navigation
  - type: mergeBranch
    head: add-navigation
  - type: deleteBranch
    branch: add-navigation
  - type: createPullRequest
    title: Add Git tips
    body: 00_add-git-tips.md
    head: add-git-tips
    action_id: gitTipsPR
  - type: createStatus
    state: "failure"
    failure:
      description: >-
        Please make sure that all words are spelled correctly.
    sha: ab8fe26dfd24d863908a5074e704358023d11109
    context: failing-build

steps:

# Step 1: 
  - title: References within issues
    description: Find and close the duplicate cross-linked issue
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: gate
        left: '%payload.issue.title%'
        operator: ===
        right: Welcome to this repository
        else:
        - type: respond
          with: e-unexpected.md
          data:
            expected: close the issue titled **Welcome to this repository**
      - type: createIssue
        title: Fix the sidebar
        body: 01_sidebar.md
        comments:
        - 01_crosslink.md
        action_id: similarIssue
      - type: createProjectBoard
        name: v1.0.0
        description: Planning for v1.0.0 release
        columns:
        - Backlog
        - In progress
        action_id: projectBoard
      - type: octokit
        method: projects.createColumn
        project_id: '%actions.projectBoard.data.id%'
        name: Done
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        action_id: doneColumn
      - type: octokit
        method: projects.createCard
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        content_id: '%actions.similarIssue.data.id%'
        content_type: Issue
        column_id: '%actions.doneColumn.data.id%'
      - type: createIssue
        title: Broken sidebar
        body: 01_the-similar-crosslink.md
      - type: closeIssue
        issue: Welcome
      - type: respond
        with: 01_next-step.md
      - type: respond
        with: 01_next-step.md
        issue: Welcome

# Step 2: Crosslink
  - title: Create a crosslink
    description: Find the relevant or duplicate issue or pull request, and create a crosslink
    event: issue_comment.created
    link: '{{ repoUrl }}/issues/7'
    actions:
      - type: gate
        every: true
        gates:
          - left: '%payload.issue.title%'
            operator: ===
            right: Fix the sidebar
          - left: '(8)'
            operator: test
            right: '%payload.comment.body%'
        else:
          - type: respond
            with: e-unexpected.md
            data:
              expected: comment on the issue titled **Fix the sidebar** with the comment `#8`, the number of the similar issue
      - type: respond
        with: 02_find-commit.md

# Step 3:
  - title: Find a commit
    description: Find the commit associated with the creation of the sidebar file
    event: issue_comment.created
    link: '{{ repoUrl }}/issues/7'
    actions:
      - type: gate
        every: true
        gates:
          - left: '%payload.issue.title%'
            operator: ===
            right: Fix the sidebar
          - left: '(312f87)'
            operator: test
            right: '%payload.comment.body%'
        else:
          - type: respond
            with: e-unexpected.md
            data:
              expected: comment on the issue titled **Fix the sidebar** with the comment `312f872f79e50d505f02be5ddc97b3f7504d0189`, the SHA of the commit we're looking for
      - type: respond
        with: 03_context.md
        data:
          commitId: '%payload.comment.body%'

# Step 4: Finding info and context
  - title: Find context
    description: Create a link to the pull request where the commit was created
    event: project_card.created
    link: '{{ repoUrl }}/issues/7'
    actions:
      - type: gate
        left: '(5)'
        operator: test
        right: '%payload.project_card.content_url%'
        else:
        - type: respond
          with: e-unexpected.md
          issue: Fix the sidebar
          data:
            expected: add pull request \#5 to the Done column of the v1.0.0 project
      - type: respond
        with: 04_find-broken-build.md
        issue: Fix the sidebar

# Step 5:
  - title: Assign yourself
    description: Assign yourself to the pull request with a broken build
    event: pull_request.assigned
    link: '{{ repoUrl }}/issues/7'
    actions:
      - type: gate
        left: '%payload.pull_request.title%'
        operator: ===
        right: Add Git tips
        else:
          - type: respond
            with: e-unexpected.md
            data:
              expected: 'assign yourself to the pull request titled **Add Git tips**'
      - type: respond
        with: 05_fix-build.md

# Step 6: Something to do with tests
  - title: Fix the broken build
    description: Fix the broken build in the pull request with a new commit
    event: pull_request.synchronize
    link: '{{ repoUrl }}/pull/6'
    actions:
      - type: getFileContents
        filename: docs/git-tips.md
        action_id: fileContents
      - type: gate
        every: true
        gates:
          - left: '%payload.pull_request.title%'
            operator: ===
            right: Add Git tips
          - left: '(tricks)'
            operator: test
            right: '%actions.fileContents%'
        else:
          - type: respond
            with: e-unexpected.md
            data:
              expected: edit `docs/git-tips.md` on the `add-git-tips` branch so that the word "tricks" is properly spelled
      - type: createStatus
        state: success
        sha: '%payload.head_commit.id%'
      - type: respond
        with: 06_please-merge.md
        issue: Add Git tips
      
# Step 7: Merge pull request
  - title: Merge
    description: Merge the final pull request
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/6'
    actions:
      - type: gate
        every: true
        gates:
          - left: '%payload.pull_request.merged%'
          - left: '%payload.pull_request.title%'
            operator: ===
            right: Add Git tips
        else:
          - type: respond
            with: e-unexpected.md
            data:
              expected: merge the pull request titled **Add Git tips**
      - type: createIssue
        title: Congratulations!
        body: 07_congratulations.md
      - type: respond
        with: 07_final-issue.md
        issue: Add Git tips